### ISSUE TITLE
notification emails fail when having non-ascii characters in map title

### ISSUE THREAD

**Issue by hholzgra** [hholzgra/maposmatic#77]
```
Mar 16 10:09:37 print python3[3918709]: UnicodeEncodeError: 'ascii' codec can't encode characters in position 401-408: ordinal not in range(128)
Mar 16 10:09:37 print python3[3918709]:     msg = _fix_eols(msg).encode('ascii')
Mar 16 10:09:37 print python3[3918709]:   File "/usr/lib/python3.8/smtplib.py", line 868, in sendmail
Mar 16 10:09:37 print python3[3918709]:     mailer.sendmail(DAEMON_ERRORS_EMAIL_FROM, self.job.submittermail, msg)
Mar 16 10:09:37 print python3[3918709]:   File "/home/maposmatic/maposmatic/scripts/render.py", line 312, in _email_submitter
Mar 16 10:09:37 print python3[3918709]: Traceback (most recent call last):
Mar 16 10:09:37 print python3[3918709]: 2022-03-16 10:09:37,577 - maposmatic@3918709 - ERROR - Could not send notification email to the submitter!

```

**Comment by hholzgra** [comment]
See also Issue #72
